server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.92.117.116:3366/server_ip_manager?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: hqkk
    password: hqkk123
  redis:
    database: 29 # Redis数据库索引（默认为0）
    host: 47.111.89.204 # Redis服务器地址
    port: 6380  # Redis服务器端口
    password: hqkk_root # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 300 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 8 # 连接池中的最小空闲连接
    timeout: 12000ms  # 连接超时时间（毫秒）
computer:
  id: 0