server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.92.117.116:3366/server_ip_manager?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: hqkk
    password: hqkk123
computer:
  id: 1